# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmU38CUGXQGa5rIhZQrDtbz_EAaetiSv
"""

!pip install yfinance

import yfinance as yf

amd = yf.Ticker("AMD")

amd.info

amd.history(period="max")